log:
  config_name: 'base4'
  log_dir: './log/'
  model_dir: './model/'
  record_step: 1600
model:
  pretrained: True
  model_name: 'efficientnet-b5'
  num_classes: 14
optimizer:
  lr: 0.0001                                    #0.0001
  betas: !!python/tuple [0.9, 0.999]
  eps: 1.0e-8
  weight_decay: 1.0e-5                          #1.0e-5
train_loader:
  image_dir: '../'                              # Directory of ChexPert images
  label_dir: '../CheXpert-v1.0-small/train.csv' # Directory of ChexPert train label csv file
test_loader:
  image_dir: '../'                              # Directory of ChexPert images
  label_dir: '../CheXpert-v1.0-small/valid.csv' # Directory of ChexPert valid label csv file
  batchsize: 1                                  # Test need a smaller batchsize    
  numworker: 12
train_param:
  epoch: 3                                      #20
  batchsize: 4
  numworker: 12
  train_transform: !!python/tuple [] #['RandomErasing']
  model_dir: './model/'
label_info:
  num_classes: 14
  class_names: !!python/tuple ['No Finding', 'Enlarged Cardiomediastinum', 'Cardiomegaly', 'Lung Opacity',
                               'Lung Lesion', 'Edema', 'Consolidation', 'Pneumonia', 'Atelectasis', 'Pneumothorax',
                               'Pleural Effusion', 'Pleural Other', 'Fracture', 'Support Devices']
  eval_metrics: !!python/tuple [8, 2, 6, 5, 10]